# Generated by Django 3.0 on 2020-05-17 05:29

from __future__ import unicode_literals

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250, unique_for_date='contract_date')),
                ('description', models.TextField()),
                ('revenue', models.FloatField()),
                ('contract_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bought_product', models.CharField(choices=[('mri_segmentation', 'MRI Segmentation'),
                                                             ('administrative_manager', 'Administrative Manager')],
                                                    default='administrative_manager', max_length=50)),
                ('representative',
                 models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='customers_info',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-contract_date',),
            },
        ),
    ]
